version: "3.9"

services:
  # Database
  db:
    image: postgres:latest
    container_name: postgres_server
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Database management tools
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  postgres_data:
  pgadmin-data:

# How to run the containers:
# sudo docker-compose up -d  # Starts all services in detached mode
# sudo docker-compose down    # Stops all running services
